jQuery ->
    $("body").bootria()
        # Navigation bar
        .navbar({style: "navbar-static-top"})
            .brand()
            .item({title: "Goals", active: true})
            .item()
            .item()
        .end()
        # Hero unit
        .hero()
            .heading("BootRIA", 1)
            .div("well")
                .text("Build rich internet applications with Twitter Bootstrap")
            .end()
        .end()
        # Dropdown
        .container()
            .dropdown({})
                .item({title: "Home"})
                .item({title: "News"})
                .item({title: "Products"})
                .item({title: "Services"})
                .divider()
                .item({title: "Logout"})
            .end()
        .end()
        .hr()
        # Alerts
        .container()
            .row()
                .span(4)
                    .alert({title: "Succes", message: "Save successful!", style: "success", heading: true})
                .end()
                .span(4)
                    .alert({title: "Info", message: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum", style: "info"})
                .end()
                .span(4)
                    .alert({title: "Error", message: "Save successful!", style: "error"})
                .end()
            .end()
            .row()
                .span(3)
                    .alert({title: "Warning", message: "Something might by wrong!", header: true})
                .end()
                .span(6)
                    .alert({title: "Succes", message: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur!", style: "success", header: true})
                .end()
                .span(3)
                    .alert({title: "Succes", message: "Save successful!", style: "success"})
                .end()
            .end();